souffle: souffle::RamAbstractExistenceCheck Class Reference
souffle::RamAbstractExistenceCheck Class Reference
Abstract existence check for a tuple in a relation.
#include <RamCondition.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get relation.
std::vector< RamExpression * > getValues () const
Get arguments of the tuple/pattern.
RamAbstractExistenceCheck (std::unique_ptr< RamRelationReference > relRef, std::vector< std::unique_ptr< RamExpression >> vals)
Public Member Functions inherited from souffle::RamCondition
RamCondition * clone () const override=0
Create a clone (i.e.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void print (std::ostream &out=std::cout) const =0
Print RAM node.
RamNode ()=default
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
std::unique_ptr< RamRelationReference > relationRef
Relation.
std::vector< std::unique_ptr< RamExpression > > values
Pattern – nullptr if undefined.
Detailed Description
Abstract existence check for a tuple in a relation.
Definition at line 280 of file RamCondition.h.
Constructor & Destructor Documentation
RamAbstractExistenceCheck()
souffle::RamAbstractExistenceCheck::RamAbstractExistenceCheck (std::unique_ptr< RamRelationReference > relRef, std::vector< std::unique_ptr< RamExpression >> vals) inline
Definition at line 282 of file RamCondition.h.
             : relationRef(std::move(relRef)), values(std::move(vals)) {}
Member Function Documentation
apply()
void souffle::RamAbstractExistenceCheck::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 304 of file RamCondition.h.
{
         relationRef = map(std::move(relationRef));
         for (auto& val : values) {
             val = map(std::move(val));
         }
     }
equal()
bool souffle::RamAbstractExistenceCheck::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 318 of file RamCondition.h.
References souffle::equal_targets(), and getRelation().
{
         assert(nullptr != dynamic_cast<const RamAbstractExistenceCheck*>(&node));
         const auto& other = static_cast<const RamAbstractExistenceCheck&>(node);
         return getRelation() == other.getRelation() && equal_targets(values, other.values);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamAbstractExistenceCheck::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 296 of file RamCondition.h.
{
         std::vector<const RamNode*> res = {relationRef.get()};
         for (const auto& cur : values) {
             res.push_back(cur.get());
         }
         return res;
     }
getRelation()
const RamRelation& souffle::RamAbstractExistenceCheck::getRelation () const inline
Get relation.
Definition at line 287 of file RamCondition.h.
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::RAMI::evalCond(), souffle::LVMGenerator::visitExistenceCheck(), and souffle::LVMGenerator::visitProvenanceExistenceCheck().
{
         return *relationRef->get();
     }
getValues()
std::vector<RamExpression*> souffle::RamAbstractExistenceCheck::getValues () const inline
Get arguments of the tuple/pattern.
Definition at line 292 of file RamCondition.h.
References souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalCond(), souffle::RamLevelAnalysis::getLevel(), souffle::RamIndexAnalysis::getSearchSignature(), souffle::RamIndexAnalysis::isTotalSignature(), souffle::LVMGenerator::visitExistenceCheck(), and souffle::LVMGenerator::visitProvenanceExistenceCheck().
{
         return toPtrVector(values);
     }
Field Documentation
relationRef
std::unique_ptr<RamRelationReference> souffle::RamAbstractExistenceCheck::relationRef protected
Relation.
Definition at line 313 of file RamCondition.h.
values
std::vector<std::unique_ptr<RamExpression> > souffle::RamAbstractExistenceCheck::values protected
Pattern – nullptr if undefined.
Definition at line 316 of file RamCondition.h.
The documentation for this class was generated from the following file:
RamCondition.h