souffle: souffle::RAMIIndex Class Reference
souffle::RAMIIndex Class Reference
#include <RAMIIndex.h>
Data Structures
struct comparator
Public Types
using index_set = btree_multiset< const RamDomain *, comparator, std::allocator< const RamDomain * >, 512 >
using iterator = index_set::iterator
Public Member Functions
std::pair< iterator, iterator > equalRange (const RamDomain *value)
return start and end iterator of an equal range
bool exists (const RamDomain *value)
check whether tuple exists in index
std::pair< iterator, iterator > getIteratorPair () const
return start and end iterator of the index set
void insert (const RamDomain *tuple)
add tuple to the index
template<class Iter >
void insert (const Iter &a, const Iter &b)
add tuples to the index via an iterator
std::pair< iterator, iterator > lowerUpperBound (const RamDomain *low, const RamDomain *high)
return start and end iterator of a range
const LexOrder & order () const
void print (std::ostream &out) const
enables the index to be printed
void purge ()
purge all hashes of index
RAMIIndex (LexOrder order)
RAMIIndex (const RAMIIndex &&index)
Private Types
using LexOrder = std::vector< int >
Private Attributes
index_set::btree_operation_hints< 1 > operation_hints
Operation hints.
index_set set
set storing tuple pointers of table
const LexOrder theOrder
retain the index order used to construct an object of this class
Detailed Description
Definition at line 30 of file RAMIIndex.h.
Member Typedef Documentation
index_set
using souffle::RAMIIndex::index_set = btree_multiset<const RamDomain*, comparator, std::allocator<const RamDomain*>, 512>
Definition at line 71 of file RAMIIndex.h.
iterator
using souffle::RAMIIndex::iterator = index_set::iterator
Definition at line 73 of file RAMIIndex.h.
LexOrder
using souffle::RAMIIndex::LexOrder = std::vector<int> private
Definition at line 31 of file RAMIIndex.h.
Constructor & Destructor Documentation
RAMIIndex() [1/2]
souffle::RAMIIndex::RAMIIndex (LexOrder order) inline
Definition at line 75 of file RAMIIndex.h.
 : theOrder(std::move(order)), set(comparator(theOrder), comparator(theOrder)) {}
RAMIIndex() [2/2]
souffle::RAMIIndex::RAMIIndex (const RAMIIndex && index) inline
Definition at line 77 of file RAMIIndex.h.
 : theOrder(std::move(index.theOrder)), set(std::move(index.set)) {}
Member Function Documentation
equalRange()
std::pair<iterator, iterator> souffle::RAMIIndex::equalRange (const RamDomain * value) inline
return start and end iterator of an equal range
Definition at line 121 of file RAMIIndex.h.
References lowerUpperBound().
{
         return lowerUpperBound(value, value);
     }
exists()
bool souffle::RAMIIndex::exists (const RamDomain * value) inline
check whether tuple exists in index
Definition at line 103 of file RAMIIndex.h.
References operation_hints.
Referenced by souffle::RAMIRelation::exists().
{
         return set.find(value, operation_hints) != set.end();
     }
getIteratorPair()
std::pair<iterator, iterator> souffle::RAMIIndex::getIteratorPair () const inline
return start and end iterator of the index set
Definition at line 132 of file RAMIIndex.h.
{
         return std::pair<iterator, iterator>(set.begin(), set.end());
     }
insert() [1/2]
void souffle::RAMIIndex::insert (const RamDomain * tuple) inline
add tuple to the index
precondition: tuple does not exist in the index
Definition at line 88 of file RAMIIndex.h.
References operation_hints.
{
         set.insert(tuple, operation_hints);
     }
insert() [2/2]
template<class Iter > void souffle::RAMIIndex::insert (const Iter & a, const Iter & b) inline
add tuples to the index via an iterator
precondition: the tuples do not exist in the index
Definition at line 98 of file RAMIIndex.h.
{
         set.insert(a, b);
     };
lowerUpperBound()
std::pair<iterator, iterator> souffle::RAMIIndex::lowerUpperBound (const RamDomain * low, const RamDomain * high) inline
return start and end iterator of a range
Definition at line 126 of file RAMIIndex.h.
References operation_hints.
Referenced by equalRange().
{
         return std::pair<iterator, iterator>(
                 set.lower_bound(low, operation_hints), set.upper_bound(high, operation_hints));
     }
order()
const LexOrder& souffle::RAMIIndex::order () const inline
Definition at line 79 of file RAMIIndex.h.
References theOrder.
{
         return theOrder;
     }
print()
void souffle::RAMIIndex::print (std::ostream & out) const inline
enables the index to be printed
Definition at line 114 of file RAMIIndex.h.
{
         set.printStats(out);
         out << "\n";
         set.printTree(out);
     }
purge()
void souffle::RAMIIndex::purge () inline
purge all hashes of index
Definition at line 108 of file RAMIIndex.h.
References operation_hints.
                  {
         set.clear();
         operation_hints.clear();
     }
Field Documentation
operation_hints
index_set::btree_operation_hints<1> souffle::RAMIIndex::operation_hints private
Operation hints.
Definition at line 144 of file RAMIIndex.h.
Referenced by exists(), insert(), lowerUpperBound(), and purge().
set
index_set souffle::RAMIIndex::set private
set storing tuple pointers of table
Definition at line 141 of file RAMIIndex.h.
theOrder
const LexOrder souffle::RAMIIndex::theOrder private
retain the index order used to construct an object of this class
Definition at line 138 of file RAMIIndex.h.
Referenced by order().
The documentation for this class was generated from the following file:
RAMIIndex.h