souffle: souffle::LVMProgInterface Class Reference
souffle::LVMProgInterface Class Reference
Implementation of SouffleProgram interface for an interpreter instance.
#include <LVMProgInterface.h>
Public Member Functions
void dumpInputs (std::ostream &) override
Dump inputs: not implemented.
void dumpOutputs (std::ostream &) override
Dump outputs: not implemented.
void executeSubroutine (std::string name, const std::vector< RamDomain > &args, std::vector< RamDomain > &ret, std::vector< bool > &err) override
Run subroutine.
SymbolTable & getSymbolTable () override
Get symbol table.
void loadAll (std::string) override
Load input data: not implemented.
LVMProgInterface (LVMInterface &interp)
void printAll (std::string) override
Print output data: not implemented.
void run (size_t) override
Run program instance: not implemented.
void runAll (std::string, std::string, size_t) override
Load data, run program instance, store data: not implemented.
~LVMProgInterface () override
Public Member Functions inherited from souffle::SouffleProgram
std::vector< Relation * > getAllRelations () const
std::vector< Relation * > getInputRelations () const
std::vector< Relation * > getInternalRelations () const
std::vector< Relation * > getOutputRelations () const
Relation * getRelation (const std::string &name) const
void purgeInputRelations ()
void purgeInternalRelations ()
void purgeOutputRelations ()
virtual ~SouffleProgram ()=default
Private Attributes
LVMInterface & exec
std::vector< LVMRelInterface * > interfaces
const RamProgram & prog
SymbolTable & symTable
Additional Inherited Members
Protected Member Functions inherited from souffle::SouffleProgram
void addRelation (const std::string &name, Relation *rel, bool isInput, bool isOutput)
Detailed Description
Implementation of SouffleProgram interface for an interpreter instance.
Definition at line 174 of file LVMProgInterface.h.
Constructor & Destructor Documentation
LVMProgInterface()
souffle::LVMProgInterface::LVMProgInterface (LVMInterface & interp) inline
Definition at line 176 of file LVMProgInterface.h.
References souffle::LVMRelInterface::attrNames, souffle::RamRelation::getArg(), souffle::RamRelation::getArgTypeQualifier(), souffle::RamRelation::getArity(), souffle::RamRelation::getName(), souffle::RamRelationStatement::getRelation(), i, n, souffle::LVMRelInterface::name, souffle::LVMRelInterface::types, and souffle::visitDepthFirst().
             : prog(*interp.getTranslationUnit().getProgram()), exec(interp),
               symTable(interp.getTranslationUnit().getSymbolTable()) {
         uint32_t id = 0;
         // Retrieve AST Relations and store them in a map
         std::map<std::string, const RamRelation*> map;
         visitDepthFirst(prog, [&](const RamRelation& rel) { map[rel.getName()] = &rel; });
         // Build wrapper relations for Souffle's interface
         for (auto& relPtr : exec.getRelationMap()) {
             if (relPtr == nullptr) {
                 continue;
             }
             const auto& name = relPtr->getName();
             auto& interpreterRel = *relPtr;
             assert(map[name]);
             const RamRelation& rel = *map[name];
             // construct types and names vectors
             std::vector<std::string> types;
             std::vector<std::string> attrNames;
             for (size_t i = 0; i < rel.getArity(); i++) {
                 std::string t = rel.getArgTypeQualifier(i);
                 types.push_back(t);
                 std::string n = rel.getArg(i);
                 attrNames.push_back(n);
             }
             auto* interface =
                     new LVMRelInterface(interpreterRel, symTable, rel.getName(), types, attrNames, id);
             interfaces.push_back(interface);
             bool input;
             bool output;
             visitDepthFirst(prog, [&](const RamStore& store) {
                 if (store.getRelation() == rel) {
                     output = true;
                 }
             });
             visitDepthFirst(prog, [&](const RamLoad& load) {
                 if (load.getRelation() == rel) {
                     input = true;
                 }
             });
             addRelation(rel.getName(), interface, input, output);
             id++;
         }
     }
~LVMProgInterface()
souffle::LVMProgInterface::~LVMProgInterface () inline override
Definition at line 224 of file LVMProgInterface.h.
{
         for (auto* interface : interfaces) {
             delete interface;
         }
     }
Member Function Documentation
dumpInputs()
void souffle::LVMProgInterface::dumpInputs (std::ostream &) inline override virtual
Dump inputs: not implemented.
Implements souffle::SouffleProgram.
Definition at line 243 of file LVMProgInterface.h.
 {}
dumpOutputs()
void souffle::LVMProgInterface::dumpOutputs (std::ostream &) inline override virtual
Dump outputs: not implemented.
Implements souffle::SouffleProgram.
Definition at line 246 of file LVMProgInterface.h.
 {}
executeSubroutine()
void souffle::LVMProgInterface::executeSubroutine (std::string name, const std::vector< RamDomain > & args, std::vector< RamDomain > & ret, std::vector< bool > & err) inline override virtual
Run subroutine.
Reimplemented from souffle::SouffleProgram.
Definition at line 249 of file LVMProgInterface.h.
{
         exec.executeSubroutine(name, args, ret, err);
     }
getSymbolTable()
SymbolTable& souffle::LVMProgInterface::getSymbolTable () inline override virtual
Get symbol table.
Implements souffle::SouffleProgram.
Definition at line 255 of file LVMProgInterface.h.
References souffle::LVMRelInterface::symTable.
{
         return symTable;
     }
loadAll()
void souffle::LVMProgInterface::loadAll (std::string) inline override virtual
Load input data: not implemented.
Implements souffle::SouffleProgram.
Definition at line 237 of file LVMProgInterface.h.
 {}
printAll()
void souffle::LVMProgInterface::printAll (std::string) inline override virtual
Print output data: not implemented.
Implements souffle::SouffleProgram.
Definition at line 240 of file LVMProgInterface.h.
 {}
run()
void souffle::LVMProgInterface::run (size_t) inline override virtual
Run program instance: not implemented.
Reimplemented from souffle::SouffleProgram.
Definition at line 231 of file LVMProgInterface.h.
 {}
runAll()
void souffle::LVMProgInterface::runAll (std::string , std::string , size_t) inline override virtual
Load data, run program instance, store data: not implemented.
Implements souffle::SouffleProgram.
Definition at line 234 of file LVMProgInterface.h.
 {}
Field Documentation
exec
LVMInterface& souffle::LVMProgInterface::exec private
Definition at line 261 of file LVMProgInterface.h.
interfaces
std::vector<LVMRelInterface*> souffle::LVMProgInterface::interfaces private
Definition at line 263 of file LVMProgInterface.h.
prog
const RamProgram& souffle::LVMProgInterface::prog private
Definition at line 260 of file LVMProgInterface.h.
symTable
SymbolTable& souffle::LVMProgInterface::symTable private
Definition at line 262 of file LVMProgInterface.h.
The documentation for this class was generated from the following file:
LVMProgInterface.h