souffle: souffle::RAMIContext Class Reference
souffle::RAMIContext Class Reference
Evaluation context for Interpreter operations.
#include <RAMIContext.h>
Public Member Functions
void addReturnValue (RamDomain val, bool err=false)
RamDomain * allocateNewTuple (size_t size)
Allocate a tuple.
RamDomain getArgument (size_t i) const
const std::vector< RamDomain > & getArguments () const
std::vector< bool > & getReturnErrors () const
std::vector< RamDomain > & getReturnValues () const
const RamDomain *& operator[] (size_t index)
const RamDomain *const & operator[] (size_t index) const
RAMIContext (size_t size=0)
void setArguments (const std::vector< RamDomain > &a)
void setReturnErrors (std::vector< bool > &retErrs)
void setReturnValues (std::vector< RamDomain > &retVals)
virtual ~RAMIContext ()=default
Private Attributes
std::vector< std::unique_ptr< RamDomain[]> > allocatedDataContainer
const std::vector< RamDomain > * args = nullptr
std::vector< const RamDomain * > data
std::vector< bool > * returnErrors = nullptr
std::vector< RamDomain > * returnValues = nullptr
Detailed Description
Evaluation context for Interpreter operations.
Definition at line 29 of file RAMIContext.h.
Constructor & Destructor Documentation
RAMIContext()
souffle::RAMIContext::RAMIContext (size_t size = 0) inline
Definition at line 37 of file RAMIContext.h.
References ~RAMIContext().
 : data(size) {}
~RAMIContext()
virtual souffle::RAMIContext::~RAMIContext () virtual default
Referenced by RAMIContext().
Member Function Documentation
addReturnValue()
void souffle::RAMIContext::addReturnValue (RamDomain val, bool err = false) inline
Definition at line 69 of file RAMIContext.h.
References err.
Referenced by souffle::RAMI::evalOp().
{
         assert(returnValues != nullptr && returnErrors != nullptr);
         returnValues->push_back(val);
         returnErrors->push_back(err);
     }
allocateNewTuple()
RamDomain* souffle::RAMIContext::allocateNewTuple (size_t size) inline
Allocate a tuple.
allocatedDataContainer has the ownership of those tuples.
Definition at line 53 of file RAMIContext.h.
{
         std::unique_ptr<RamDomain[]> newTuple(new RamDomain[size]);
         allocatedDataContainer.push_back(std::move(newTuple));
         // Return the reference as raw pointer.
         return allocatedDataContainer.back().get();
     }
getArgument()
RamDomain souffle::RAMIContext::getArgument (size_t i) const inline
Definition at line 91 of file RAMIContext.h.
References i.
Referenced by souffle::RAMI::evalExpr().
{
         assert(args != nullptr && i < args->size() && "argument out of range");
         return (*args)[i];
     }
getArguments()
const std::vector<RamDomain>& souffle::RAMIContext::getArguments () const inline
Definition at line 83 of file RAMIContext.h.
References args.
Referenced by souffle::RAMI::evalOp(), and souffle::RAMI::evalStmt().
{
         return *args;
     }
getReturnErrors()
std::vector<bool>& souffle::RAMIContext::getReturnErrors () const inline
Definition at line 75 of file RAMIContext.h.
References returnErrors.
Referenced by souffle::RAMI::evalOp(), and souffle::RAMI::evalStmt().
{
         return *returnErrors;
     }
getReturnValues()
std::vector<RamDomain>& souffle::RAMIContext::getReturnValues () const inline
Definition at line 61 of file RAMIContext.h.
References returnValues.
Referenced by souffle::RAMI::evalOp(), and souffle::RAMI::evalStmt().
{
         return *returnValues;
     }
operator[]() [1/2]
const RamDomain*& souffle::RAMIContext::operator[] (size_t index) inline
Definition at line 40 of file RAMIContext.h.
{
         if (index >= data.size()) {
             data.resize((index + 1));
         }
         return data[index];
     }
operator[]() [2/2]
const RamDomain* const& souffle::RAMIContext::operator[] (size_t index) const inline
Definition at line 47 of file RAMIContext.h.
{
         return data[index];
     }
setArguments()
void souffle::RAMIContext::setArguments (const std::vector< RamDomain > & a) inline
Definition at line 87 of file RAMIContext.h.
Referenced by souffle::RAMI::evalOp(), souffle::RAMI::evalStmt(), and souffle::RAMI::executeSubroutine().
{
         args = &a;
     }
setReturnErrors()
void souffle::RAMIContext::setReturnErrors (std::vector< bool > & retErrs) inline
Definition at line 79 of file RAMIContext.h.
Referenced by souffle::RAMI::evalOp(), souffle::RAMI::evalStmt(), and souffle::RAMI::executeSubroutine().
{
         returnErrors = &retErrs;
     }
setReturnValues()
void souffle::RAMIContext::setReturnValues (std::vector< RamDomain > & retVals) inline
Definition at line 65 of file RAMIContext.h.
Referenced by souffle::RAMI::evalOp(), souffle::RAMI::evalStmt(), and souffle::RAMI::executeSubroutine().
{
         returnValues = &retVals;
     }
Field Documentation
allocatedDataContainer
std::vector<std::unique_ptr<RamDomain[]> > souffle::RAMIContext::allocatedDataContainer private
Definition at line 34 of file RAMIContext.h.
args
const std::vector<RamDomain>* souffle::RAMIContext::args = nullptr private
Definition at line 33 of file RAMIContext.h.
Referenced by getArguments().
data
std::vector<const RamDomain*> souffle::RAMIContext::data private
Definition at line 30 of file RAMIContext.h.
returnErrors
std::vector<bool>* souffle::RAMIContext::returnErrors = nullptr private
Definition at line 32 of file RAMIContext.h.
Referenced by getReturnErrors().
returnValues
std::vector<RamDomain>* souffle::RAMIContext::returnValues = nullptr private
Definition at line 31 of file RAMIContext.h.
Referenced by getReturnValues().
The documentation for this class was generated from the following file:
RAMIContext.h