souffle: souffle::LVMRelation Class Reference
souffle::LVMRelation Class Reference
A relation, composed of a collection of indexes.
#include <LVMRelation.h>
Data Structures
class Iterator
Support for-each iteration for LVMRelation.
Public Member Functions
Iterator begin () const
bool contains (const TupleRef &tuple) const
Tests whether this relation contains the given tuple.
bool empty () const
Check if the relation is empty.
Iterator end () const
bool exists (const TupleRef &tuple) const
Check if a tuple exists in realtion.
virtual void extend (const LVMRelation &rel)
Extend another relation.
size_t getArity () const
Return arity.
const std::vector< std::string > & getAttributeTypeQualifiers () const
Return the attribute types.
size_t getLevel () const
Return the level of the relation.
const std::string & getName () const
Return the relation name.
virtual bool insert (const TupleRef &tuple)
Add the given tuple to this relation.
virtual bool insert (const RamDomain *tuple)
Add the given tuple to this relation.
void insert (const LVMRelation &other)
Add all entries of the given relation to this relation.
LVMRelation (std::size_t arity, const std::string &name, const std::vector< std::string > &attributeTypes, const MinIndexSelection &orderSet, IndexFactory factory=&createBTreeIndex)
Creates a relation, build all necessary indexes.
LVMRelation (LVMRelation &other)=delete
virtual void purge ()
Clear all indexes.
Stream range (const size_t &indexPos, const TupleRef &low, const TupleRef &high) const
Obtains a stream covering the interval between the two given entries.
void removeIndex (const size_t &indexPos)
Drops an index from the maintained indexes.
Stream scan () const
Obtains a stream to scan the entire relation.
void setLevel (size_t level)
Set level.
size_t size () const
Return number of tuples in relation (full-order)
void swap (LVMRelation &other)
Swaps the content of this and the given relation, including the installed indexes.
virtual ~LVMRelation ()=default
Protected Attributes
size_t arity
std::vector< std::string > attributeTypes
std::vector< std::unique_ptr< LVMIndex > > indexes
size_t level = 0
LVMIndex * main
std::string relName
Detailed Description
A relation, composed of a collection of indexes.
Definition at line 26 of file LVMRelation.h.
Constructor & Destructor Documentation
LVMRelation() [1/2]
souffle::LVMRelation::LVMRelation (std::size_t arity, const std::string & name, const std::vector< std::string > & attributeTypes, const MinIndexSelection & orderSet, IndexFactory factory = &createBTreeIndex)
Creates a relation, build all necessary indexes.
Definition at line 24 of file LVMRelation.cpp.
References arity, end(), souffle::MinIndexSelection::getAllOrders(), i, indexes, and main.
         : relName(name), arity(arity), attributeTypes(attributeTypes) {
     for (auto order : orderSet.getAllOrders()) {
         // Expand the order to a total order
         std::set<int> set;
         for (const auto& i : order) {
             set.insert(i);
         }
         for (std::size_t i = 0; i < arity; ++i) {
             if (set.find(i) == set.end()) {
                 order.push_back(i);
             }
         }
         indexes.push_back(factory(Order(order)));
     }
     // Use the first index as default main index
     main = indexes[0].get();
 }
LVMRelation() [2/2]
souffle::LVMRelation::LVMRelation (LVMRelation & other) delete
~LVMRelation()
virtual souffle::LVMRelation::~LVMRelation () virtual default
Member Function Documentation
begin()
Iterator souffle::LVMRelation::begin () const inline
Definition at line 71 of file LVMRelation.h.
Referenced by souffle::LVMRelInterface::begin().
{
         return *this;
     }
contains()
bool souffle::LVMRelation::contains (const TupleRef & tuple) const
Tests whether this relation contains the given tuple.
Definition at line 68 of file LVMRelation.cpp.
References souffle::LVMIndex::contains(), and main.
Referenced by insert().
{
     return main->contains(tuple);
 }
empty()
bool souffle::LVMRelation::empty () const
Check if the relation is empty.
Definition at line 105 of file LVMRelation.cpp.
References souffle::LVMIndex::empty(), and main.
Referenced by setLevel().
{
     return main->empty();
 }
end()
Iterator souffle::LVMRelation::end () const inline
Definition at line 75 of file LVMRelation.h.
References insert(), souffle::LVMRelation::Iterator::Iterator(), and removeIndex().
Referenced by souffle::LVMRelInterface::end(), and LVMRelation().
{
         return Iterator();
     }
exists()
bool souffle::LVMRelation::exists (const TupleRef & tuple) const
Check if a tuple exists in realtion.
Definition at line 115 of file LVMRelation.cpp.
References souffle::LVMIndex::contains(), and main.
Referenced by souffle::LVMRelInterface::contains(), and setLevel().
{
     return main->contains(tuple);
 }
extend()
void souffle::LVMRelation::extend (const LVMRelation & rel) virtual
Extend another relation.
Reimplemented in souffle::LVMEqRelation.
Definition at line 119 of file LVMRelation.cpp.
Referenced by setLevel().
 {}
getArity()
size_t souffle::LVMRelation::getArity () const
Return arity.
Definition at line 97 of file LVMRelation.cpp.
References arity.
Referenced by souffle::LVMRelInterface::contains(), souffle::LVMRelInterface::getArity(), souffle::LVMRelInterface::insert(), and setLevel().
{
     return this->arity;
 }
getAttributeTypeQualifiers()
const std::vector< std::string > & souffle::LVMRelation::getAttributeTypeQualifiers () const
Return the attribute types.
Definition at line 93 of file LVMRelation.cpp.
References attributeTypes.
Referenced by setLevel().
{
     return this->attributeTypes;
 }
getLevel()
size_t souffle::LVMRelation::getLevel () const
Return the level of the relation.
Definition at line 85 of file LVMRelation.cpp.
References level.
Referenced by setLevel().
{
     return this->level;
 }
getName()
const std::string & souffle::LVMRelation::getName () const
Return the relation name.
Definition at line 89 of file LVMRelation.cpp.
References relName.
Referenced by setLevel().
{
     return this->relName;
 }
insert() [1/3]
bool souffle::LVMRelation::insert (const TupleRef & tuple) virtual
Add the given tuple to this relation.
Reimplemented in souffle::LVMIndirectRelation, and souffle::LVMEqRelation.
Definition at line 52 of file LVMRelation.cpp.
References indexes, souffle::LVMIndex::insert(), and main.
Referenced by end(), souffle::LVM::execute(), souffle::LVMEqRelation::extend(), souffle::LVMRelInterface::insert(), insert(), and souffle::LVMEqRelation::insert().
{
     if (!main->insert(tuple)) return false;
     for (const auto& cur : indexes) {
         if (cur.get() == main) continue;
         cur->insert(tuple);
     }
     return true;
 }
insert() [2/3]
virtual bool souffle::LVMRelation::insert (const RamDomain * tuple) inline virtual
Add the given tuple to this relation.
Reimplemented in souffle::LVMIndirectRelation.
Definition at line 93 of file LVMRelation.h.
References contains(), high, insert(), low, range(), scan(), and swap().
{
         return insert(TupleRef(tuple, arity));
     }
insert() [3/3]
void souffle::LVMRelation::insert (const LVMRelation & other)
Add all entries of the given relation to this relation.
Definition at line 61 of file LVMRelation.cpp.
References insert(), and scan().
{
     // TODO: cover this in a smarter way
     for (const auto& cur : other.scan()) {
         insert(cur);
     }
 }
purge()
void souffle::LVMRelation::purge () virtual
Clear all indexes.
Reimplemented in souffle::LVMIndirectRelation.
Definition at line 109 of file LVMRelation.cpp.
References indexes.
Referenced by souffle::LVMRelInterface::purge(), and setLevel().
{
     for (auto& index : indexes) {
         index->clear();
     }
 }
range()
Stream souffle::LVMRelation::range (const size_t & indexPos, const TupleRef & low, const TupleRef & high) const
Obtains a stream covering the interval between the two given entries.
Definition at line 76 of file LVMRelation.cpp.
References indexes.
Referenced by insert().
{
     auto& pos = indexes[indexPos];
     return pos->range(low, high);
 }
removeIndex()
void souffle::LVMRelation::removeIndex (const size_t & indexPos)
Drops an index from the maintained indexes.
All but one index may be removed.
Definition at line 46 of file LVMRelation.cpp.
References indexes.
Referenced by end().
{
     // All but one index can be removed, default full index can't be removed.
     assert(indexes.size() > 1 || indexPos != 0);
     indexes[indexPos].reset(nullptr);
 }
scan()
Stream souffle::LVMRelation::scan () const
Obtains a stream to scan the entire relation.
Definition at line 72 of file LVMRelation.cpp.
References main, and souffle::LVMIndex::scan().
Referenced by souffle::LVMEqRelation::extend(), and insert().
{
     return main->scan();
 }
setLevel()
void souffle::LVMRelation::setLevel (size_t level) inline
Set level.
Definition at line 126 of file LVMRelation.h.
References empty(), exists(), extend(), getArity(), getAttributeTypeQualifiers(), getLevel(), getName(), level, purge(), and size().
{
         this->level = level;
     }
size()
size_t souffle::LVMRelation::size () const
Return number of tuples in relation (full-order)
Definition at line 101 of file LVMRelation.cpp.
References main, and souffle::LVMIndex::size().
Referenced by souffle::LVM::execute(), setLevel(), and souffle::LVMRelInterface::size().
{
     return main->size();
 }
swap()
void souffle::LVMRelation::swap (LVMRelation & other)
Swaps the content of this and the given relation, including the installed indexes.
Definition at line 81 of file LVMRelation.cpp.
References indexes.
Referenced by insert().
{
     indexes.swap(other.indexes);
 }
Field Documentation
arity
size_t souffle::LVMRelation::arity protected
Definition at line 180 of file LVMRelation.h.
Referenced by souffle::LVMEqRelation::extend(), getArity(), souffle::LVMEqRelation::insert(), souffle::LVMIndirectRelation::insert(), and LVMRelation().
attributeTypes
std::vector<std::string> souffle::LVMRelation::attributeTypes protected
Definition at line 183 of file LVMRelation.h.
Referenced by getAttributeTypeQualifiers().
indexes
std::vector<std::unique_ptr<LVMIndex> > souffle::LVMRelation::indexes protected
Definition at line 186 of file LVMRelation.h.
Referenced by insert(), souffle::LVMIndirectRelation::insert(), LVMRelation(), purge(), souffle::LVMIndirectRelation::purge(), range(), removeIndex(), and swap().
level
size_t souffle::LVMRelation::level = 0 protected
Definition at line 192 of file LVMRelation.h.
Referenced by getLevel(), and setLevel().
main
LVMIndex* souffle::LVMRelation::main protected
Definition at line 189 of file LVMRelation.h.
Referenced by contains(), empty(), exists(), insert(), souffle::LVMIndirectRelation::insert(), LVMRelation(), scan(), and size().
relName
std::string souffle::LVMRelation::relName protected
Definition at line 177 of file LVMRelation.h.
Referenced by getName().
The documentation for this class was generated from the following files:
LVMRelation.h
LVMRelation.cpp